// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoVYuqYKII-qciux_w6pIGlQ2yU195o4k',
    appId: '1:289243144285:android:4365fdaf8e94012b836db4',
    messagingSenderId: '289243144285',
    projectId: 'test-efbeb',
    storageBucket: 'test-efbeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Dk5-n9WW9cC2bW5VK01Y464ARvcBc54',
    appId: '1:289243144285:ios:4c138bbd157c6ec1836db4',
    messagingSenderId: '289243144285',
    projectId: 'test-efbeb',
    storageBucket: 'test-efbeb.appspot.com',
    iosBundleId: 'com.example.riverpodProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUq7jtjuAZ7eSMMD_QoV4Cc3yS0Hdmd9o',
    appId: '1:289243144285:web:19c1f510f9f4757f836db4',
    messagingSenderId: '289243144285',
    projectId: 'test-efbeb',
    authDomain: 'test-efbeb.firebaseapp.com',
    storageBucket: 'test-efbeb.appspot.com',
    measurementId: 'G-VYX9JSGC7B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Dk5-n9WW9cC2bW5VK01Y464ARvcBc54',
    appId: '1:289243144285:ios:4c138bbd157c6ec1836db4',
    messagingSenderId: '289243144285',
    projectId: 'test-efbeb',
    storageBucket: 'test-efbeb.appspot.com',
    iosBundleId: 'com.example.riverpodProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUq7jtjuAZ7eSMMD_QoV4Cc3yS0Hdmd9o',
    appId: '1:289243144285:web:46dc6462709f9d24836db4',
    messagingSenderId: '289243144285',
    projectId: 'test-efbeb',
    authDomain: 'test-efbeb.firebaseapp.com',
    storageBucket: 'test-efbeb.appspot.com',
    measurementId: 'G-G7T79LW2VD',
  );

}